sudo: false
os:
  - linux
language: node_js
node_js:
  - "10"
  - "12"
  - "14"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.5
      - g++-4.8
before_install:
  - sh -e /etc/init.d/xvfb start
env:
  global:
    - DISPLAY=:99.0
    - RANDOM_TESTS_REPEAT=100
  matrix:
    - CXX=g++-4.8 TEST_SUITE=unit
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "14"
      env: CXX=g++-4.8 TEST_SUITE=lint
    - os: linux
      node_js: "14"
      env: CXX=clang++ TEST_SUITE=unit
script: npm run $TEST_SUITE
